
\echo :GROUP_NAME
\echo :METRIC
\echo :MONITOR_TYPE

CREATE OR REPLACE FUNCTION MONMON(GROUP_NAME CHARACTER, METRIC CHARACTER, MTYPE INTEGER)
  RETURNS CHARACTER VARYING(32) AS 
$BODY$
  DECLARE 
    MONITOR_NAMED CHARACTER VARYING(32);
    TABLE_NAME CHARACTER VARYING(128);
  BEGIN
    MONITOR_NAMED := (SELECT TYPE_NAME FROM MONITOR_TYPES WHERE MONITOR_TYPE=MTYPE);
    TABLE_NAME := GROUP_NAME || '_' || METRIC || '_' || MONITOR_NAMED || '_MONITOR';
    RAISE NOTICE 'Table Name: %',TABLE_NAME;
    EXECUTE FORMAT('
      CREATE TABLE %I 
      (
        CHANNEL_ID    INTEGER NOT NULL,
        SMPL_TIME     TIMESTAMP WITH TIME ZONE NOT NULL,
        SMPL_VALUE    DOUBLE PRECISION,
        PRIMARY KEY   (CHANNEL_ID,SMPL_VALUE)
      )',LOWER(TABLE_NAME));

    RETURN MONITOR_NAMED;
  END
$BODY$
LANGUAGE plpgsql;

SELECT MONMON(:GROUP_NAME,:METRIC,:MONITOR_TYPE);

