
GRANT USAGE ON SCHEMA RUNCON_PRD TO RUNCON_READER,RUNCON_WRITER,PUBLIC;

GRANT SELECT ON ALL TABLES IN SCHEMA RUNCON_PRD TO RUNCON_READER,RUNCON_WRITER,PUBLIC;

GRANT INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA RUNCON_PRD TO RUNCON_WRITER;

