-- Create new columns in table RUNCON_PRD.MONITOR_MAP to hold last two 
-- values and their times

ALTER TABLE MONITOR_MAP ADD COLUMN 
  LAST_SMPL_TIME_A TIMESTAMP WITH TIME ZONE;

ALTER TABLE MONITOR_MAP ADD COLUMN 
  LAST_SMPL_TIME_B TIMESTAMP WITH TIME ZONE;

ALTER TABLE MONITOR_MAP ADD COLUMN 
  LAST_SMPL_VALUE_A DOUBLE PRECISION;

ALTER TABLE MONITOR_MAP ADD COLUMN 
  LAST_SMPL_VALUE_B DOUBLE PRECISION;

ALTER TABLE MONITOR_MAP ADD COLUMN 
  LAST_SMPL CHAR(1);

CREATE OR REPLACE FUNCTION UPDATE_LAST_VALUE()
  RETURNS TRIGGER AS $$
DECLARE 
  LAST_TAG CHAR(1);
BEGIN
  SELECT LAST_SMPL INTO LAST_TAG FROM MONITOR_MAP WHERE CHANNEL_ID=NEW.CHANNEL_ID;
  IF LAST_TAG == 'A' THEN 
    UPDATE CHANNEL SET 
           LAST_SMPL_TIME_B    = NEW.SMPL_TIME,
           LAST_SMPL_VALUE_B   = NEW.SMPL_VALUE,
           LAST_SMPL           = 'B'
    WHERE MONITOR_MAP.CHANNEL_ID=NEW.CHANNEL_ID;
  ELSE 
    UPDATE CHANNEL SET 
           LAST_SMPL_TIME_A    = NEW.SMPL_TIME,
           LAST_SMPL_VALUE_A   = NEW.SMPL_VALUE,
           LAST_SMPL           = 'A'
    WHERE MONITOR_MAP.CHANNEL_ID=NEW.CHANNEL_ID;
  END IF;

  RETURN NEW;
END; $$
LANGUAGE plpgsql;


CREATE TRIGGER LAST_VALUE AFTER INSERT ON tpc_rms_mean_monitor
  FOR EACH ROW 
  EXECUTE PROCEDURE UPDATE_LAST_VALUE();



