-- Create new columns in table RUNCON_PRD.MONITOR_MAP to hold last two 
-- values and their times

-- ALTER TABLE RUNCON_PRD.MONITOR_MAP ADD COLUMN 
--  LAST_SMPL_TIME_A TIMESTAMP WITH TIME ZONE;
--
--ALTER TABLE RUNCON_PRD.MONITOR_MAP ADD COLUMN 
--  LAST_SMPL_TIME_B TIMESTAMP WITH TIME ZONE;
--
--ALTER TABLE RUNCON_PRD.MONITOR_MAP ADD COLUMN 
--  LAST_SMPL_VALUE_A DOUBLE PRECISION;
--
--ALTER TABLE RUNCON_PRD.MONITOR_MAP ADD COLUMN 
--  LAST_SMPL_VALUE_B DOUBLE PRECISION;
--
--ALTER TABLE RUNCON_PRD.MONITOR_MAP ADD COLUMN 
--  LAST_SMPL CHAR(1);
--
CREATE OR REPLACE FUNCTION RUNCON_PRD.UPDATE_LAST_VALUE()
  RETURNS TRIGGER AS $$
DECLARE 
  LAST_TAG CHAR(1);
BEGIN
  SELECT LAST_SMPL INTO LAST_TAG FROM RUNCON_PRD.MONITOR_MAP WHERE CHANNEL_ID=NEW.CHANNEL_ID;
  IF LAST_TAG = 'A' THEN 
    UPDATE RUNCON_PRD.MONITOR_MAP SET 
           LAST_SMPL_TIME_B    = NEW.SMPL_TIME,
           LAST_SMPL_VALUE_B   = NEW.SMPL_VALUE,
           LAST_SMPL           = 'B'
    WHERE CHANNEL_ID=NEW.CHANNEL_ID;
  ELSE 
    UPDATE RUNCON_PRD.MONITOR_MAP SET 
           LAST_SMPL_TIME_A    = NEW.SMPL_TIME,
           LAST_SMPL_VALUE_A   = NEW.SMPL_VALUE,
           LAST_SMPL           = 'A'
    WHERE CHANNEL_ID=NEW.CHANNEL_ID;
  END IF;

  RETURN NEW;
END; $$
LANGUAGE plpgsql;


DROP TRIGGER IF EXISTS LAST_VALUE ON RUNCON_PRD.tpc_channel_rms_mean_monitor;

CREATE TRIGGER LAST_VALUE AFTER INSERT ON RUNCON_PRD.tpc_channel_rms_mean_monitor
  FOR EACH ROW 
  EXECUTE PROCEDURE RUNCON_PRD.UPDATE_LAST_VALUE();



