
CREATE TABLE RUNCON_PRD.MONITOR_TYPES
(
  MONITOR_TYPE    INTEGER                  NOT NULL, 
  TYPE_NAME       CHARACTER VARYING(32)    NOT NULL,
  PRIMARY KEY (MONITOR_TYPE)
);

INSERT INTO RUNCON_PRD.MONITOR_TYPES VALUES (0,'MEAN');
INSERT INTO RUNCON_PRD.MONITOR_TYPES VALUES (1,'MEDIAN');
INSERT INTO RUNCON_PRD.MONITOR_TYPES VALUES (2,'MODE');
INSERT INTO RUNCON_PRD.MONITOR_TYPES VALUES (3,'MAX');
INSERT INTO RUNCON_PRD.MONITOR_TYPES VALUES (4,'MIN');
INSERT INTO RUNCON_PRD.MONITOR_TYPES VALUES (5,'LAST');

CREATE TABLE RUNCON_PRD.MONITOR_MAP
(
  GROUP_NAME         CHARACTER VARYING(128)   NOT NULL,
  METRIC             CHARACTER VARYING(32)    NOT NULL,
  CHANNEL_ID         INTEGER                  NOT NULL,
  MONITOR_TYPE       INTEGER                  NOT NULL REFERENCES MONITOR_TYPES(MONITOR_TYPE),
  POSTGRES_TABLE     CHARACTER VARYING(128)   NOT NULL,
  TIME_INTERVAL      DOUBLE PRECISION         NOT NULL,
  CREATE_TIME        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  LAST_SMPL_TIME_A   TIMESTAMP WITH TIME ZONE,
  LAST_SMPL_TIME_B   TIMESTAMP WITH TIME ZONE,
  LAST_SMPL_VALUE_A  DOUBLE PRECISION,
  LAST_SMPL_VALUE_B  DOUBLE PRECISION,
  LAST_SMPL          CHAR(1),
  PRIMARY KEY (GROUP_NAME,METRIC,CHANNEL_ID,MONITOR_TYPE)
);

